### ISSUE TITLE
Setting overlap_threshold to .2 throws error

### ISSUE THREAD

**Issue by grant-roy** [EpistasisLab/ebic.jl#14] opened 2022-04-28 22:17 UTC
@prenc I also noticed that setting the overlap threshold to .2 (and maybe lower) and clusters to say 80 or so causes an error.

**Comment by prenc** [comment] 2022-04-29 09:16
@grant-roy Please provide the test case on which it crashes for reproduction. With `example_input.csv` the low values of the *overlap_threshold* seem to work correctly.

**Comment by grant-roy** [comment] 2022-04-29 20:50
@prenc 

Below is a screenshot
<img width="950" alt="Screen Shot 2022-04-29 at 1 45 25 PM" src="https://user-images.githubusercontent.com/1839666/166067028-27c5fd83-c3b7-43eb-83d9-71f3bed95bdb.png">


The input matrix has about 19,000 rows and ~350 columns (because it is a medical dataset unfortunately I can't provide the matrix itself). I can maybe try and make a synthetic dataset, if that helps, but won't be able to get to that for a few days.

**Comment by prenc** [comment] 2022-05-02 19:37
@grant-roy, I figured out what the problem is. Even though you set the overlap threshold to 0.2, the rank list (stores the best chromosomes) has only 38 of them while you are looking for 80. In the next version, it will be fixed, and only as many as there are up to max_biclusters will be taken.

Also, most of the currently fixed parameters will be available as arguments, so I'd suggest using a bigger population and reproduction size for such a dataset.

**Comment by grant-roy** [comment] 2022-05-03 21:51
@prenc  I'll try it in the next version. Thanks for having a look. 

I will also try to optimize the parameters, I was going to ask about these, glad to hear they will be available as arguments. Let me know if you have any other suggestions, thanks again.

**Comment by prenc** [comment] 2022-05-03 21:57
@grant-roy The next version is almost ready (together with a new reworked README). You can try it out from [here](https://github.com/EpistasisLab/EBIC.jl/tree/v0.2.0). Let me know if there is still something you need. We're going to continue developing the algorithm with new features.

**Comment by grant-roy** [comment] 2022-05-03 22:08
@prenc sounds great, thanks.  I'll try it out and let you know how it goes (and offer any suggestions for features if I have any).

**Closed as completed** 2024-01-24 18:27 UTC
